name: Build OpenWrt x86_64

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Space cleanup
        run: |
          docker rmi $(docker images -q) 2>/dev/null || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* mongodb* snapd* 2>/dev/null || true
          sudo -E apt-get update
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz libnsl-dev ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Clone OpenWrt source
        run: |
          git clone --depth 1 https://github.com/coolsnowwolf/lede -b master openwrt

      - name: Setup feeds
        run: |
          cp -f feeds.conf.default openwrt/feeds.conf.default
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load config
        run: |
          cp -f configs/x86_64.config openwrt/.config
          cd openwrt
          make defconfig

      - name: Run custom scripts
        run: |
          chmod +x diy-part2.sh
          cd openwrt
          "${GITHUB_WORKSPACE}/diy-part2.sh"

      - name: Download packages
        run: |
          cd openwrt
          make download -j$(nproc) || make download -j1 V=s
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          cd openwrt
          echo "$(nproc) thread build"
          make -j$(nproc) || make -j1 V=s
          df -h

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_x86_64
          path: openwrt/bin/targets/
